name: stock_trading_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_improved_scrolling: ^0.0.3
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  supabase_flutter: ^2.3.4
  web_smooth_scroll: ^1.1.0
  webview_flutter: ^4.7.0
  webview_flutter_web: ^0.2.2+4
  webviewx_plus: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
